# Generated by Django 5.2.7 on 2025-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=15, help_text='Time limit in minutes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
    ]
