# Generated by Django 5.2.7 on 2025-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_description_quiz_quiz_status_quiz_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('answer', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
