# Generated by Django 5.2.7 on 2025-11-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_aiquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='selected_option',
            new_name='user_answer',
        ),
        migrations.RenameField(
            model_name='userquizattempt',
            old_name='end_time',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='userquizattempt',
            old_name='start_time',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='status',
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='score_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='subcategory',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.aiquestion'),
        ),
    ]
