# Generated by Django 5.2.7 on 2025-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_rename_selected_option_useranswer_user_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='helpful_feedback',
            field=models.BooleanField(null=True),
        ),
    ]
