# Generated by Django 5.2.7 on 2025-11-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_questionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='learning_source',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
